/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.dashboard.app.kafka.account.avro.model;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class AccountCreatedAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1465026182668235303L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AccountCreatedAvroModel\",\"namespace\":\"com.dashboard.app.kafka.account.avro.model\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"initialBalance\",\"type\":{\"type\":\"bytes\",\"logicalType\":\"decimal\",\"precision\":10,\"scale\":2}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.UUIDConversion());
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.DecimalConversion());
  }

  private static final BinaryMessageEncoder<AccountCreatedAvroModel> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AccountCreatedAvroModel> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AccountCreatedAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AccountCreatedAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AccountCreatedAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AccountCreatedAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AccountCreatedAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AccountCreatedAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AccountCreatedAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.util.UUID id;
  private java.math.BigDecimal initialBalance;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AccountCreatedAvroModel() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param initialBalance The new value for initialBalance
   */
  public AccountCreatedAvroModel(java.util.UUID id, java.math.BigDecimal initialBalance) {
    this.id = id;
    this.initialBalance = initialBalance;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return initialBalance;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      new org.apache.avro.Conversions.UUIDConversion(),
      new org.apache.avro.Conversions.DecimalConversion(),
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.util.UUID)value$; break;
    case 1: initialBalance = (java.math.BigDecimal)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.util.UUID getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.util.UUID value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'initialBalance' field.
   * @return The value of the 'initialBalance' field.
   */
  public java.math.BigDecimal getInitialBalance() {
    return initialBalance;
  }


  /**
   * Sets the value of the 'initialBalance' field.
   * @param value the value to set.
   */
  public void setInitialBalance(java.math.BigDecimal value) {
    this.initialBalance = value;
  }

  /**
   * Creates a new AccountCreatedAvroModel RecordBuilder.
   * @return A new AccountCreatedAvroModel RecordBuilder
   */
  public static com.dashboard.app.kafka.account.avro.model.AccountCreatedAvroModel.Builder newBuilder() {
    return new com.dashboard.app.kafka.account.avro.model.AccountCreatedAvroModel.Builder();
  }

  /**
   * Creates a new AccountCreatedAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AccountCreatedAvroModel RecordBuilder
   */
  public static com.dashboard.app.kafka.account.avro.model.AccountCreatedAvroModel.Builder newBuilder(com.dashboard.app.kafka.account.avro.model.AccountCreatedAvroModel.Builder other) {
    if (other == null) {
      return new com.dashboard.app.kafka.account.avro.model.AccountCreatedAvroModel.Builder();
    } else {
      return new com.dashboard.app.kafka.account.avro.model.AccountCreatedAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new AccountCreatedAvroModel RecordBuilder by copying an existing AccountCreatedAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new AccountCreatedAvroModel RecordBuilder
   */
  public static com.dashboard.app.kafka.account.avro.model.AccountCreatedAvroModel.Builder newBuilder(com.dashboard.app.kafka.account.avro.model.AccountCreatedAvroModel other) {
    if (other == null) {
      return new com.dashboard.app.kafka.account.avro.model.AccountCreatedAvroModel.Builder();
    } else {
      return new com.dashboard.app.kafka.account.avro.model.AccountCreatedAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for AccountCreatedAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AccountCreatedAvroModel>
    implements org.apache.avro.data.RecordBuilder<AccountCreatedAvroModel> {

    private java.util.UUID id;
    private java.math.BigDecimal initialBalance;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.dashboard.app.kafka.account.avro.model.AccountCreatedAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.initialBalance)) {
        this.initialBalance = data().deepCopy(fields()[1].schema(), other.initialBalance);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing AccountCreatedAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(com.dashboard.app.kafka.account.avro.model.AccountCreatedAvroModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.initialBalance)) {
        this.initialBalance = data().deepCopy(fields()[1].schema(), other.initialBalance);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.util.UUID getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.dashboard.app.kafka.account.avro.model.AccountCreatedAvroModel.Builder setId(java.util.UUID value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.dashboard.app.kafka.account.avro.model.AccountCreatedAvroModel.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'initialBalance' field.
      * @return The value.
      */
    public java.math.BigDecimal getInitialBalance() {
      return initialBalance;
    }


    /**
      * Sets the value of the 'initialBalance' field.
      * @param value The value of 'initialBalance'.
      * @return This builder.
      */
    public com.dashboard.app.kafka.account.avro.model.AccountCreatedAvroModel.Builder setInitialBalance(java.math.BigDecimal value) {
      validate(fields()[1], value);
      this.initialBalance = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'initialBalance' field has been set.
      * @return True if the 'initialBalance' field has been set, false otherwise.
      */
    public boolean hasInitialBalance() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'initialBalance' field.
      * @return This builder.
      */
    public com.dashboard.app.kafka.account.avro.model.AccountCreatedAvroModel.Builder clearInitialBalance() {
      initialBalance = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AccountCreatedAvroModel build() {
      try {
        AccountCreatedAvroModel record = new AccountCreatedAvroModel();
        record.id = fieldSetFlags()[0] ? this.id : (java.util.UUID) defaultValue(fields()[0]);
        record.initialBalance = fieldSetFlags()[1] ? this.initialBalance : (java.math.BigDecimal) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AccountCreatedAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<AccountCreatedAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AccountCreatedAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<AccountCreatedAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }


  @Override
  public int hashCode() {
    int result = 1;
    result = 31 * result + (id == null ? 0 : id.hashCode());
    result = 31 * result + (initialBalance == null ? 0 : initialBalance.hashCode());
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof AccountCreatedAvroModel)) {
      return false;
    }
    AccountCreatedAvroModel other = (AccountCreatedAvroModel) o;
    if (!java.util.Objects.equals(this.id, other.id)) {
      return false;
    }
    if (!java.util.Objects.equals(this.initialBalance, other.initialBalance)) {
      return false;
    }
    return true;
  }
}










