package com.dashboard.app.financial.entity.domain.model.entity

import com.dashboard.app.common.domain.model.entity.AggregateRoot
import com.dashboard.app.common.domain.model.valueobject.FinancialEntityId

/**
 * Represents a financial entity with a unique identifier and a name.
 *
 * @property name The name of the financial entity.
 * @property id The unique identifier for the financial entity, generated by default if not provided.
 */
class FinancialEntity(
    id: FinancialEntityId,
    var name: String,
): AggregateRoot<FinancialEntityId>(id) {

    companion object {

        /**
         * Initializes a new instance of the FinancialEntity class with a generated unique identifier and the specified name.
         *
         * @param name The name of the financial entity.
         * @return A new instance of FinancialEntity with a unique identifier and the provided name.
         */
        fun initialize(name: String) = FinancialEntity(FinancialEntityId.random(), name)

    }

    override fun toString(): String = "FinancialEntity(id='$id', name='$name')"

}