package com.dashboard.app.financial.entity.domain.model.entity

import com.dashboard.app.common.domain.model.entity.AggregateRoot
import com.dashboard.app.common.domain.model.valueobject.FinancialEntityId

/**
 * Represents a financial entity with a unique identifier and a name.
 *
 * @property name The name of the financial entity.
 * @property id The unique identifier for the financial entity, generated by default if not provided.
 */
class FinancialEntity(
    var name: String,
    id: FinancialEntityId = FinancialEntityId.random()
): AggregateRoot<FinancialEntityId>(id) {

    override fun toString(): String = "FinancialEntity(id='$id', name='$name')"

}