spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # locates services registered with eureka and creates routes for them
          lower-case-service-id: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8071/eureka/