spring:

  application:
    name: financial-entity-service

  config:
    import: "optional:configserver:"

  mvc:
    apiversion:
      default: v1
      use:
        header: api-version
  jpa:
    # Forces the persistence context to stay open. So that the view layer can trigger the proxy initialization.
    # This will keep a database connection open for a long time which would have terrible effects on database performance.
    open-in-view: false
    # Show each SQL on the locks which is good for debug purposes.
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    # The binaryTransfer, reWriteBatchedInserts and stringtype parameters are added to optimize the performance of batch inserts and updates.
    # For more details, see https://jdbc.postgresql.org/documentation/head/performance.html#batch-performance.
    # With binaryTransfer parameter the data will be transferred from Postgres server to JDBC driver in Binary form.
    # So it'll be transferred faster as this will eliminate the need for conversion like converting a number from their text representation to their Binary representation.
    # With reWriteBatchedInserts parameter the JDBC driver will rewrite the batch inserts into a single insert statement with multiple values.
    # This can significantly improve the performance of batch inserts as it reduces the number of round trips to the database.
    # With stringtype=unspecified parameter the JDBC driver will send all string parameters as String type instead of trying to guess the type based on the value.
    # This prevents for example checking on UUID types which can be time-consuming and can lead to performance issues.
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=account&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    platform: postgres

  profiles:
    default: dev

account-service:
  financial-entity-created-topic-name: financial-entity-created
  financial-entity-updated-topic-name: financial-entity-updated
  account-created-topic-name: account-created
  account-updated-topic-name: account-updated

kafka-config:
  bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
  schema-registry-url-key: schema.registry.url
  schema-registry-url: http://localhost:8081
  num-of-partitions: 3
  replication-factor: 3

kafka-producer-config:
  key-serializer-class: org.apache.kafka.common.serialization.StringSerializer
  value-serializer-class: io.confluent.kafka.serializers.KafkaAvroSerializer
  compression-type: snappy
  acks: all
  batch-size: 16384
  batch-size-boost-factor: 100
  linger-ms: 5
  request-timeout-ms: 60000
  retry-count: 5

kafka-consumer-config:
  key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
  financial-entity-consumer-group-id: financial-entity-topic-consumer
  account-consumer-group-id: account-topic-consumer
  auto-offset-reset: earliest
  specific-avro-reader-key: specific.avro.reader
  specific-avro-reader: true
  batch-listener: true
  auto-startup: true
  concurrency-level: 3
  session-timeout-ms: 10000
  heartbeat-interval-ms: 3000
  max-poll-interval-ms: 300000
  max-poll-records: 500
  max-partition-fetch-bytes-default: 1048576
  max-partition-fetch-bytes-boost-factor: 1
  poll-timeout-ms: 150