name: Deployment

on:
  push:
    branches: [ "main" ]
    paths: [ '/infraestructure/**' ]

  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo This is a deployment for the main infraestructure
