name: Module One CI

on:
  pull_request:
    paths: [ "module_one/**" ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run project build
        run: echo Build
  sonarqube:
    name: SonarQube
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v6
        with:
          projectBaseDir: module_one
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  test:
    name: Test
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: echo Tests
