name: Financial Entity Service CI

on:
  pull_request:
    paths: [ "service-financial-entity/**" ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run: mvn install -N && mvn install -f service-common -DskipTests && mvn install -f service-financial-entity -DskipTests
  test:
    name: Unit Tests
    needs: [ build ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Test with Maven
        run: cd service-financial-entity && mvn test
